# This is the configuration file for Supabase Edge Functions.
# Learn more at https://supabase.com/docs/guides/functions

[functions]
  [functions.generate-task-description]
  verify_jwt = true
  
  [functions.transcribe-audio]
  verify_jwt = true
  
  [functions.generate-follow-up]
  verify_jwt = true
  
  [functions.analyze-client-data]
  verify_jwt = true
  
  [functions.generate-business-insights]
  verify_jwt = true
  
  [functions.optimize-pricing]
  verify_jwt = true

[global.env]
  OPENAI_API_KEY = "env(OPENAI_API_KEY)" 